[server]
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#40E0D0"
backgroundColor = "#0A0A0A"
secondaryBackgroundColor = "#141414"
textColor = "#FFFFFF"
font = "sans serif" 